name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      # NOTE(mnaser): This is a workaround due to the fact that certain pods
      #               will not run inside GHA such as Percona XtraDB Cluster.
      - name: Run IPv6 workarounds
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test
