name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  terratest:
    runs-on: ubuntu-focal
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test
